name: Cypress-Cucumber Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
      - name: Install xpath
        uses: actions/checkout@v2
        with:
          command: npm i cypress-xpath
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          command: npm run cypress:execution
